#!/bin/bash
# This script mounts all standard drives used on laptop

"$TOOLS_DIR/mount-drive-d"
"$TOOLS_DIR/mount-drive-e"
"$TOOLS_DIR/mount-drive-f"
"$TOOLS_DIR/mount-drive-g"
"$TOOLS_DIR/mount-drive-h"
"$TOOLS_DIR/mount-drive-i"
